"""Добавил каскадное удаление корзины

Revision ID: 153c33edeba8
Revises: 76ae0f9a97e6
Create Date: 2026-09-06 21:40:52.859685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153c33edeba8'
down_revision: Union[str, Sequence[str], None] = '76ae0f9a97e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cart_items_cart_id_fkey'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'carts', ['cart_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('carts_user_id_fkey'), 'carts', type_='foreignkey')
    op.create_foreign_key(None, 'carts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'carts', type_='foreignkey')
    op.create_foreign_key(op.f('carts_user_id_fkey'), 'carts', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_cart_id_fkey'), 'cart_items', 'carts', ['cart_id'], ['id'])
    # ### end Alembic commands ###
