"""Исправлено поведение при удалении для заказов и позиций

Revision ID: 29e7e34e63e6
Revises: 153c33edeba8
Create Date: 2026-09-07 00:22:41.302411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e7e34e63e6'
down_revision: Union[str, Sequence[str], None] = '153c33edeba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('delivery_address_saved', sa.String(), nullable=False))
    op.alter_column('orders', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(op.f('orders_address_id_fkey'), 'orders', type_='foreignkey')
    op.drop_constraint(op.f('orders_user_id_fkey'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_user_id_fkey'), 'orders', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('orders_address_id_fkey'), 'orders', 'addresses', ['address_id'], ['id'], ondelete='RESTRICT')
    op.alter_column('orders', 'address_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'delivery_address_saved')
    # ### end Alembic commands ###
