"""Добавлено каскадное удаление addresses

Revision ID: 76ae0f9a97e6
Revises: 3bf4df881ead
Create Date: 2026-08-11 13:47:10.058925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76ae0f9a97e6'
down_revision: Union[str, Sequence[str], None] = '3bf4df881ead'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_addresses_user_id'), 'addresses', ['user_id'], unique=False)
    op.drop_constraint(op.f('addresses_user_id_fkey'), 'addresses', type_='foreignkey')
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_cart_items_cart_id'), 'cart_items', ['cart_id'], unique=False)
    op.create_index(op.f('ix_cart_items_product_id'), 'cart_items', ['product_id'], unique=False)
    op.drop_constraint(op.f('carts_user_id_key'), 'carts', type_='unique')
    op.create_index(op.f('ix_carts_user_id'), 'carts', ['user_id'], unique=True)
    op.create_index(op.f('ix_orders_address_id'), 'orders', ['address_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_foreign_key(None, 'orders', 'addresses', ['address_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_address_id'), table_name='orders')
    op.drop_index(op.f('ix_carts_user_id'), table_name='carts')
    op.create_unique_constraint(op.f('carts_user_id_key'), 'carts', ['user_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_cart_items_product_id'), table_name='cart_items')
    op.drop_index(op.f('ix_cart_items_cart_id'), table_name='cart_items')
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.create_foreign_key(op.f('addresses_user_id_fkey'), 'addresses', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_addresses_user_id'), table_name='addresses')
    # ### end Alembic commands ###
